name: preview

on:
  pull_request_target:
    types: [opened, reopened]
    branches: [master]

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            const issue = {
              repo: context.repo.repo,
              owner: context.repo.owner,
              issue_number: context.issue.number,
            };

            const repo = encodeURIComponent(context.repo.repo);
            const owner = encodeURIComponent(context.repo.owner);
            const prNumber = context.payload.pull_request.number;

            const previewLink = `https://pr.new/github.com/${owner}/${repo}/pull/${prNumber}`;

            const lines = [
              `[![Open in StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](${previewLink})`,
              `Run and preview this PR in [StackBlitz](${previewLink})`,
            ];

            const comment = lines.join("\n");
            const comments = await github.rest.issues.listComments(issue);

            const commentExists = comments.find((c) => c.body === comment);
            if (!commentExists) {
              await github.rest.issues.createComment({
                ...issue,
                body: comment,
              });
            }
